# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby CI"
on:
  push:
    branches: [ '**' ]
jobs:
  ruby-test:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop --parallel
      - name: Test
        run: bin/rake test
